url_: 'https://test-stand.gb.ru/gateway/login'
url_posts: 'https://test-stand.gb.ru/api/posts'
# username: 'GB202306a2eba13'
# password: '3e51388fdc'
# username: 'KatrinzZZ'
# password: '284ac1db73'
# username: 'SvetaGen71'
# password: '8d15bab768'
# token_: 'a5d0e260a40b7224b32f6fac702cf395'
username: 'ANFNA'
password: 'b38b39ea4e'
#token: '376da56bf2da06ae75ccc173d1b2bb9d'